import React from 'react'

import classes from './accounts.module.css'

import { useSelector } from 'react-redux'

function FormDisplay({setNewPassword, setConfirmPassword}) {

    const userDetails = useSelector(s=>s.user)


    return (
        <div className={classes.majorCtn}>
            <h2>Booking Details</h2>
            <form className={classes.form}>
                <div className={classes.inputCtn}>
                    <label>Name</label>
                    <input defaultValue={userDetails.name} placeholder="Ex. John Doe" disabled />
                </div>
                <div className={classes.inputCtn}>
                    <label>Reg. Number</label>
                    <input defaultValue={userDetails.regno} placeholder="Ex. RA2011003010247" disabled />
                </div>
                <div className={classes.inputCtn}>
                    <label>Department</label>
                    <input defaultValue={userDetails.dept} placeholder="Ex. School of Computing" disabled />
                </div>
                <div className={classes.inputCtn}>
                    <label>Designation</label>
                    <input defaultValue={userDetails.designation} placeholder="Ex. Staff, Faculty" disabled />
                </div>
                <div className={classes.inputCtn}>
                    <label>Official Email</label>
                    <input defaultValue={userDetails.email} placeholder="Ex. ss9261@srmist.edu.in" disabled />
                </div>
                <div className={classes.inputCtn}>
                    <label>Phone Number</label>
                    <input defaultValue={userDetails.phno} placeholder="Ex. 909934238" disabled/>
                </div>
                <div className={classes.inputCtn}>
                    <label>Account Id</label>
                    <input defaultValue={userDetails.id} placeholder="Autogenerated" disabled />
                </div>
                <div className={classes.inputCtn}>
                    <label>Account Status</label>
                    <input defaultValue={userDetails.name} placeholder="Ex. Active, Banned, Inactive" disabled='true' />
                </div>
            </form>
            <h2>Change Password</h2>
            <form className={classes.form}>
                <div className={classes.inputCtn}>
                    <label>New Password</label>
                    <input type="password" placeholder="Its secret!" onChange={e=>setNewPassword(e.target.value)}/>
                </div>
                <div className={classes.inputCtn}>
                    <label>Confirm Password</label>
                    <input type="password" placeholder="Its too secret!" onChange={e=>setConfirmPassword(e.target.value)}/>
                </div>
            </form>
        </div>
    )
}

export default FormDisplay
