import React from 'react'

import classes from './accounts.module.css'

function FormDisplay() {
    return (
        <div className={classes.majorCtn}>
            <h2>Booking Details</h2>
            <form className={classes.form}>
                <div className={classes.inputCtn}>
                    <label>Name</label>
                    <input placeholder="Ex. John Doe" disabled='true' />
                </div>
                <div className={classes.inputCtn}>
                    <label>Reg. Number</label>
                    <input placeholder="Ex. RA2011003010247" disabled='true' />
                </div>
                <div className={classes.inputCtn}>
                    <label>Department</label>
                    <input placeholder="Ex. School of Computing" disabled='true' />
                </div>
                <div className={classes.inputCtn}>
                    <label>Designation</label>
                    <input placeholder="Ex. Staff, Faculty" disabled='true' />
                </div>
                <div className={classes.inputCtn}>
                    <label>Official Email</label>
                    <input placeholder="Ex. ss9261@srmist.edu.in" disabled='true' />
                </div>
                <div className={classes.inputCtn}>
                    <label>Personal Email</label>
                    <input placeholder="Ex. xyz@gmail.com"/>
                </div>
                <div className={classes.inputCtn}>
                    <label>Account Id</label>
                    <input placeholder="Autogenerated" disabled='true' />
                </div>
                <div className={classes.inputCtn}>
                    <label>Account Status</label>
                    <input placeholder="Ex. Active, Banned, Inactive" disabled='true' />
                </div>
            </form>
            <h2>Change Password</h2>
            <form className={classes.form}>
                <div className={classes.inputCtn}>
                    <label>New Password</label>
                    <input type="password" placeholder="Its secret!"/>
                </div>
                <div className={classes.inputCtn}>
                    <label>Confirm Password</label>
                    <input type="password" placeholder="Its too secret!" />
                </div>
            </form>
        </div>
    )
}

export default FormDisplay
